version: '3.1'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    links:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password




#  nginx:
#    image: nginx:latest
#    privileged: true
#    tty: true
#    restart: "no"
#    ports:
#      - "80:80"
#      - "2225:2225"
#    volumes:
#      - ${HOST_PATH}/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ${HOST_PATH}/modsecurity.conf:/etc/nginx/modsecurity.conf:ro